        <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <!-- Loader start -->
        <div id="loader">
            <div class="loader-content">
                <div class="preloader-wrapper small active">
                    <div class="spinner-layer spinner-blue-only">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="gap-patch">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p class="loading-title">Carregando...</p>
            </div>
        </div>
        <!-- Loader end -->


        <!-- important for youtube video background -->
        <div id="youtubeVideobg"></div>

        <!-- Header Menu start -->
        <header class="main-header">
            <!-- desktop menu -->
            <div class="header-big-screen hidden-sm hidden-xs black">
                <div class="container">
                    <div class="header-inner clearfix">
                        <a href="#home" data-section="#home" class="logo menu-smooth-scroll">
                            <img src="img/EduBrand.png" alt="logo">
                        </a>
                        <nav class="menu">
                            <ul id="mobile-nav">
                                <li><a href="#why" data-section="#why" class="menu-smooth-scroll">Curso</a></li>
                                <li><a href="#features" data-section="#features" class="menu-smooth-scroll">Diferenciais</a></li>
                                <!-- <li><a href="#screenshot" data-section="#screenshot" class="menu-smooth-scroll">Screens</a></li> -->
                                <li><a href="#packages" data-section="#packages" class="menu-smooth-scroll">Preços</a></li>
                                <!-- <li><a href="#payment-method" data-section="#payment-method" class="menu-smooth-scroll">Pagamento</a></li> -->
                                <!-- <li><a href="#download" data-section="#download" class="menu-smooth-scroll">Download</a></li> -->
                                <li><a href="#team" data-section="#team" class="menu-smooth-scroll">Professor</a></li>
                                <!-- <li><a href="#blog" data-section="#blog" class="menu-smooth-scroll">Blog</a></li> -->
                                <li><a href="#contact" data-section="#contact" class="menu-smooth-scroll">Encontre</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <!-- mobile menu -->
            <div class="header-mobile-screen visible-sm visible-xs full-height black">
                <div class="header-inner full-height">
                    <div class="logo-area clearfix black">
                        <a href="#home" data-section="#home" class="logo pull-left menu-smooth-scroll">
                            <img src="img/EduBrand.png" alt="logo">
                        </a>
                        <div class="bar-area pull-right">
                            <a href="#" class="open-menu white-text"><i class="fa fa-bars"></i></a>
                            <a href="#" class="close-menu white-text"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <nav class="menu animated">
                        <ul>
                            <li class="current"><a href="#why" data-section="#why" class="menu-smooth-scroll">Curso</a></li>
                            <li><a href="#features" data-section="#features" class="menu-smooth-scroll">Diferenciais</a></li>
                            <!-- <li><a href="#screenshot" data-section="#screenshot" class="menu-smooth-scroll">Screens</a></li>-->
                            <!-- <li><a href="#packages" data-section="#packages" class="menu-smooth-scroll">Packages</a></li>-->
                            <!-- <li><a href="#download" data-section="#download" class="menu-smooth-scroll">Download</a></li>-->
                            <li><a href="#team" data-section="#team" class="menu-smooth-scroll">Professor</a></li>
                            <!-- <li><a href="#blog" data-section="#blog" class="menu-smooth-scroll">Blog</a></li>-->
                            <li><a href="#contact" data-section="#contact" class="menu-smooth-scroll">Encontre</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <!-- Header Menu end -->



        <!-- Main section start -->
        <main role="main" class="main">
            <!-- Banner Section start -->
            <section id="home" class="scroll-section banner">
                <div class="overlay overlay-one"></div>
                <div class="overlay-content text-center">
                    <div class="banner-content animated fadeOut">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h2 class="heading">Desenvolvimento de Jogos 2D para dispositivos móveis</h2>
                                    <h2 class="white-text">20, 21, 22 e 27 - 31/07/2015 às 18:30</h2>
                                    <h3 class="sub-heading white-text">Próximas turmas: 1 a 9 e 10 a 18/09 (seg à sáb)</h3>
                                    <h3 class="sub-heading" id="banner-slider-controller">Aprenda a programar desenvolvendo jogos para as maiores plataformas móveis do mundo
                                        <br>
                                        <i class="ion-social-apple"></i> <i class="ion-social-android"></i> <i class="ion-social-windows"></i>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="banner-feature">
                        <div class="banner-feature-list">
                            <i class="fa fa-globe"></i>
                            <h3 class="title">Introdução ao Mundo 2D</h3>
                        </div>
                        <div class="banner-feature-list">
                            <i class="fa fa-code"></i>
                            <h3 class="title">Introdução a Programação</h3>
                        </div>
                        <div class="banner-feature-list">
                            <div class="unreal-brand"></div>
                            <h3 class="title">Introdução à Unreal</h3>
                        </div>
                        <div class="banner-feature-list">
                            <i class="ion-iphone"></i>
                            <h3 class="title">Deploy no Dispositivo</h3>
                        </div>
                        <div class="banner-feature-list">
                            <i class="fa fa-cloud-upload"></i>
                            <h3 class="title">Publicação</h3>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Banner Section end -->

            <!-- Why this app start -->
            <section id="why" class="scroll-section section-space why-this-app section-bg-02 hidden-overflow">
                <div class="container">

                    <div class="row">
                        <div class="why-section-col col-lg-6 col-md-6 col-sm-6 hidden-xs">
                            <div class="why-slider" id="whySlider">
                                <div class="thumb-area">
                                    <img src="img/flipbook.gif" alt="">
                                </div>
                                <div class="thumb-area">
                                    <img src="img/CodeSample.png" class="no-left-space" alt="">
                                </div>
                                <div class="thumb-area">
                                    <img src="img/iphone-01-EDITED.png" class="rotate" alt="">
                                    <img src="img/android-01-EDITED.png" class="rotate" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="why-section-col col-lg-5 col-md-5 col-sm-6 col-xs-12">
                            <header><h2 class="section-title title-2">O esperar do curso?</h2></header>
                            <ul class="app-reasion-lists" id="why-feature-lists">
                                <li>
                                    <a href="#">
                                        <span class="btn left-area waves-light waves-effect"><i class="fa fa-globe"></i></span>
                                        <span class="right-area">Aula expositiva e prática das técnicas mais usadas no mundo 2D, como nos Desenhos animados da Disney.</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="btn left-area waves-light waves-effect"><i class="fa fa-code"></i></span>
                                        <span class="right-area">Lógica e boas práticas de programação. Estruturas de repetição, de condições e funções, além de animações.</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="btn left-area waves-light waves-effect"><i class="ion-iphone"></i></span>
                                        <span class="right-area">Exemplo de jogo que será feito durante o curso na parte prática de uso da Unreal Engine Environment (UE4).</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="why-section-col col-lg-1 col-md-1 hidden-sm hidden-xs"></div>
                    </div>

                </div>
            </section>
            <!-- Why this app end -->


            <!-- Amazing Feature Section start -->
            <section id="features" class="scroll-section section-space section-bg-01 amazing-feature amazing-feature-01 hidden-overflow">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="section-head">
                                <h2 class="section-title title-1">Incríveis Diferenciais</h2>
                                <p>Nós acreditamos que um curso só é bom quando dá garantias e não deixa o ex-aluno sem amparo na hora que as dificuldades aperam. Acreditamos no potencial de cada um de nossos alunos e gostamos de ouvir o como pensam e o que pensam, suas idemas e sonhos/ambições.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row feature-lists-box">
                        <div class="feature-lists feature-lists-style-one">
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-mortar-board"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Monitorias</h3>
                                        <p class="pera">
                                            Monitorias <strong class="teal-text">gratuitas</strong> sobre os tópicos como abordados durante o curso.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-comments"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Consultorias</h3>
                                        <p class="pera">
                                            Análise e consultoria a ex-alunos (projetos e trabalhos),
                                            <strong class="teal-text">podendo ser GRÁTIS</strong>.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-bullhorn"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Indicação</h3>
                                        <p class="pera">Nossos alunos são o espelho do nosso trabalho. Por isso os indicamos.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-cube"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Projeto de Código Aberto</h3>
                                        <p class="pera">Apoiamos e construímos com os alunos Frameworks de código aberto (Ciência + TI).</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-cubes"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Projetos Internos</h3>
                                        <p class="pera">Oportunidade em Projetos com a Rent$, <strong class="teal-text"> contratação remunerada de ex-alunos</strong>.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <div class="feature-list">
                                    <div class="icon-area wow rotateIn animated">
                                        <i class="fa fa-ticket"></i>
                                    </div>
                                    <div class="f-content-area">
                                        <h3 class="title">Promoção para ex-alunos</h3>
                                        <p class="pera">Desconto para ex-alunos nos próximos cursos.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Amazing Feature Section end -->


            <!-- Pricing Table Section start -->
            <section id="packages" class="scroll-section pricing-table section-space hidden-overflow">
                <div class="overlay-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <div class="section-head">
                                    <h2 class="section-title title-1">Preços por Estilo</h2>
                                    <p>Nós disponibilizamos preços que se flexibilizam em função do estilo/tipo do aluno, escolha o que mais se enquadra para você.</p>
                                </div>
                            </div>
                        </div>
                        <div class="row pricing-table-item-wrap">
                            <section class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <div class="amber accent-4 single-pricing-table pricing-table-style-one basic wow fadeInUpSmall" data-wow-offset="200">
                                    <div class="pricing-container">
                                        <div class="p-t-header white-text">
                                            <h3 class="pricing-title">Ouro</h3>
                                            <div class="best-tag color-brand z-depth-1">Melhor</div>
                                        </div>
                                        <div class="p-t-body">
                                            <p class="justify"></p>
                                            <ul>
                                                <li> <i class="fa fa-check"></i> Material Didático</li>
                                                <li> <i class="fa fa-check"></i> Monitoria</li>
                                                <li> <i class="fa fa-check"></i> Consultoria</li>
                                                <li> <i class="fa fa-check"></i> Indicação</li>
                                                <li> <i class="fa fa-check"></i> Certificado</li>
                                                <li> <i class="fa fa-check"></i> Carga: 24H em 8 encontros de 3H</li>
                                                <li> <i class="fa fa-check"></i> Plataform Virtual de Auxílio</li>
                                                <li> <i class="fa fa-check"></i> Plataform Virtual de Acompanhamento de Rendimento</li>
                                                <li> <i class="fa fa-check"></i> 10h de aulas extras virtual</li>
                                            </ul>
                                        </div>
                                        <div class="p-t-footer clearfix white-text">
                                            <div class="row">
                                                <div class="price"><span class="currency">R$</span><span>1.500,00</span></div>
                                            </div>
                                            <div class="button">
                                                <form method='post' action='https://cieloecommerce.cielo.com.br/transactional/order/buynow' target='blank'>
                                                    <input type='hidden' name='id' value='0bbbe95f-71cb-4f0a-bf89-e17a5b2228c3' />
                                                    <input type="hidden" name="merchantid" value="11f39b3b-58b8-4de7-a08a-f455356fc234" />
                                                    <input class="hide" type='image' name='submit' alt='Comprar' src='https://cieloecommerce.cielo.com.br/backoffice/Content/img/buttons/button-5-1.png' />
                                                    <button type="submit" class="btn th-btn th-btn-medium th-btn-parent white deep-purple-text">Assinar</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                            <section class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <div class="blue-grey lighten-3 black-text single-pricing-table pricing-table-style-one best wow fadeInUpSmall" data-wow-offset="200" data-wow-delay=".2s">
                                    <div class="pricing-container">
                                        <div class="p-t-header white-text">
                                            <h3 class="pricing-title">Prata</h3>
                                        </div>
                                        <div class="p-t-body">
                                            <p class="justify"></p>
                                            <ul>
                                                <li> <i class="fa fa-check"></i> Material Didático</li>
                                                <li> <i class="fa fa-check"></i> Monitoria</li>
                                                <li> <i class="fa fa-check"></i> Certificado</li>
                                                <li> <i class="fa fa-check"></i> Carga: 24H em 8 encontros de 3H</li>
                                                <li> <i class="fa fa-check"></i> Plataform Virtual de Acompanhamento de Rendimento</li>
                                                <li> <i class="fa fa-check"></i> 5h de aulas extras virtual</li>
                                            </ul>
                                        </div>
                                        <div class="p-t-footer clearfix white-text">
                                            <div class="row">
                                                <div class="price"><span class="currency">R$</span><span>1.000,00</span></div>
                                            </div>
                                            <div class="button">
                                                <form method='post' action='https://cieloecommerce.cielo.com.br/transactional/order/buynow' target='blank'>
                                                    <input type='hidden' name='id' value='b4e6ece7-7592-456a-89ac-edc1585ffb07  ' />
                                                    <input type="hidden" name="merchantid" value="11f39b3b-58b8-4de7-a08a-f455356fc234" />
                                                    <input class="hide" type='image' name='submit' alt='Comprar' src='https://cieloecommerce.cielo.com.br/backoffice/Content/img/buttons/button-5-1.png' />
                                                    <button type="submit" class="btn th-btn th-btn-medium th-btn-parent white deep-purple-text">Assinar</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                            <section class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                <div class="cooper black-text single-pricing-table pricing-table-style-one pro wow fadeInUpSmall" data-wow-offset="200" data-wow-delay=".4s">
                                    <div class="pricing-container">
                                        <div class="p-t-header white-text">
                                            <h3 class="pricing-title">Bronze</h3>
                                        </div>
                                        <div class="p-t-body">
                                            <ul>
                                                <li> <i class="fa fa-check"></i> Material Didático</li>
                                                <li> <i class="fa fa-check"></i> Monitoria</li>
                                                <li> <i class="fa fa-check"></i> Certificado</li>
                                                <li> <i class="fa fa-check"></i> Carga: 24H em 8 encontros de 3H</li>
                                            </ul>
                                        </div>
                                        <div class="p-t-footer clearfix white-text">
                                            <div class="row">
                                                <div class="price"><span class="currency">R$</span><span>750,00</span></div>
                                            </div>
                                            <div class="button">
                                                <form method='post' action='https://cieloecommerce.cielo.com.br/transactional/order/buynow' target='blank'>
                                                    <input type='hidden' name='id' value='2193a227-a1ab-4a23-a29a-fad64b556283' />
                                                    <input type="hidden" name="merchantid" value="11f39b3b-58b8-4de7-a08a-f455356fc234" />
                                                    <input class="hide" type='image' name='submit' alt='Comprar' src='https://cieloecommerce.cielo.com.br/backoffice/Content/img/buttons/button-5-1.png' />
                                                    <button type="submit" href='#payment_modal' class="btn th-btn th-btn-medium th-btn-parent white deep-purple-text">Assinar</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Pricing Table Section end -->


            <!-- Team Member Section start -->
            <section id="team" class="scroll-section team-member section-space">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="section-head">
                                <h2 class="section-title title-1">Professor</h2>
                                <p>
                                    <strong>Pós-Graduação:</strong> Engenharia de Software - Universidade Municipal de São Carlos |
                                    <strong>WEB:</strong> 3 anos |
                                    <strong>MobileApps:</strong> 4 anos |
                                    <strong>Jogos:</strong> 2 anos
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row team-members-wrap">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 col-xxs-12">
                            <div class="single-team-wrap team-theme-01 text-center wow fadeInUpSmall">
                                <div class="single-team">
                                    <div class="team-member-img">
                                        <img src="img/Trab-Logo-ZP.png" alt="Team member pic">
                                    </div>
                                    <div class="team-member-info">
                                        <div class="info-area-top">
                                            <ul class="social team-social">
                                                <li><a href="https://play.google.com/store/apps/details?id=br.com.zeropaper.app" target="_blank" class="btn color-brand bg-white"><i class="fa fa-android"></i></a></li>
                                                <li><a href="https://itunes.apple.com/br/app/zeropaper/id892377391?mt=8" target="_blank" class="btn color-brand bg-white"><i class="fa fa-apple"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="info-area-bottom">
                                            <h3 class="t-m-name">ZeroPaper</h3>
                                            <h5 class="t-m-designation">Ruby On Rails & PhoneGap</h5>
                                            <h5 class="t-m-designation">WEB & Mobile</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 col-xxs-12">
                            <div class="single-team-wrap team-theme-01 text-center wow fadeInUpSmall" data-wow-delay=".2s">
                                <div class="single-team">
                                    <div class="team-member-img">
                                        <img src="img/Trab-Logo-PGS.png" alt="Team member pic">
                                    </div>
                                    <div class="team-member-info">
                                        <div class="info-area-top">
                                            <ul class="social team-social">
                                                <li></li>
                                            </ul>
                                        </div>
                                        <div class="info-area-bottom">
                                            <h3 class="t-m-name">PGS</h3>
                                            <h5 class="t-m-designation">Ruby On Rails - WEB</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 col-xxs-12">
                            <div class="single-team-wrap team-theme-01 text-center wow fadeInUpSmall" data-wow-delay=".4s">
                                <div class="single-team">
                                    <div class="team-member-img">
                                        <img src="img/Trab-Logo-BB.png" alt="Team member pic">
                                    </div>
                                    <div class="team-member-info">
                                        <div class="info-area-top">
                                            <ul class="social team-social">
                                                <li><a target="_blank" href="https://play.google.com/store/apps/details?id=br.com.bb.oewallet" class="btn color-brand bg-white"><i class="fa fa-android"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="info-area-bottom">
                                            <h3 class="t-m-name">OuroCard-e</h3>
                                            <h5 class="t-m-designation">Android - Mobile - BB</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Team Member Section end -->


            <!-- Map And Contact Section start -->
            <section class="map-section">
                <div class="map-header-area overlay-brand">
                    <h2>Encontre-nos no Google Map</h2>
                </div>

                <!-- Map Area start -->
                <div class="map">
                    <div id="map"></div>
                </div>
                <!-- Map Area end -->
            </section>
            <!-- Map And Contact Section end -->


            <!-- Contact Area start -->
            <section id="contact" class="contact scroll-section">
                <div class="container">
                    <a href="#packages" data-section="#packages" class="btn contact-location-toggle-btn wow bounce" data-wow-duration="1.5s">
                        <i class="ion-paper-airplane"></i>
                    </a>

                    <div class="contact-content-wrapper">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12 hidden-xxs">
                                <div class="contact-info">
                                    <h3 class="contact-title">Informação de Contato</h3>
                                    <ul class="contact-info-lists">
                                        <li><a href="#"><span class="btn"><i class="ion-ios-location"></i></span>SHN Quadra 02, Executive Office Tower - 426, Brasília DF</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-call"></i></span>061 8130-0410</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-mail"></i></span>ilton@rents.com.br</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-globe"></i></span>edu.rents.com.br</a></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12">
                                <div class="contact-form cu-form">
                                    <h3 class="contact-title visible-xxs">Contact Us</h3>
                                    <form action="http://mailler.comeze.com" id="contactForm">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="input-field">
                                                    <label for="contactName">Nome completo de Contato</label>
                                                    <input id="contactName" type="text" name="contactName">
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="input-field">
                                                    <label for="contactEmail">E-mail para resposta</label>
                                                    <input id="contactEmail" type="text" name="contactEmail">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="input-field">
                                                    <label for="contactSubject">Assunto do contato</label>
                                                    <input id="contactSubject" type="text" name="contactSubject">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="input-field">
                                                    <label for="contactMessage">Mensagem - Dúvida - Elogios - Reclamações</label>
                                                    <textarea id="contactMessage" class="materialize-textarea" rows="4" name="contactMessage"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="">
                                                    <center>
                                                        <input type="submit" class="btn th-btn th-btn-small th-btn-default" value="Submeter">
                                                        <div class="form-message z-depth-1" style="display:none"></div>
                                                    </center>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-xxs-12 visible-xxs">
                                <div class="contact-info">
                                    <ul class="contact-info-lists">
                                        <li><a href="#"><span class="btn"><i class="ion-ios-location"></i></span>SHN Quadra 02, Executive Office Tower - 426, Brasília DF</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-call"></i></span>061 8130-0410</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-mail"></i></span>ilton@rents.com.br</a></li>
                                        <li><a href="#"><span class="btn"><i class="ion-android-globe"></i></span>edu.rents.com.br</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Contact Area end -->
        </main>
        <!-- Main section end -->



        <!-- Footer area start -->
        <footer class="main-footer">
            <div class="top">
                <div class="container">
                    <div class="footer-logo">
                        <img src="img/EduBrand.png" alt="logo">
                    </div>
                </div>
            </div>
            <div class="bottom">
                <div class="container">
                    <p>&copy; 2015 Rent$ Educational. All Rights Reserved.</p>
                </div>
            </div>
        </footer>
        <!-- Footer area end -->
